### ISSUE TITLE
Issue for step_2 of Electron Wannier Transport Tutorial

### ISSUE THREAD

**Issue by ZengZezhu** [mir-group/phoebe#156]
Dear Phoebe Team, 

I successfully performed the calculations of step 1 (scf calculation) of tutorial-2 in phoebe (silicon). While I encountered a issue for the step-2 of phonon calculations. The program is stopped and a error occurs: "Electron-phonon only for metals". 

Now I am sure that the issue comes from the setting of electron_phonon = "epa", and if I delete this command, the program can run well. Could you tell me what should I do in this case? Is this setting crucial for the next calculations?

Cheers,
zezhu

**Comment by jcoulter12** [comment]
Hi Zezhu, 

Are you using the patched version of QE to do the calculation? I think if you are, then this should not be an issue. 
This error message exists in unmodified copies of QE, but not the copy we provide. 

Did you carefully follow step 1 of the tutorial? 
https://phoebe.readthedocs.io/en/develop/tutorials/elWanTransport.html#step-1-patch-quantum-espresso

Let me know!
Jenny

**Comment by ZengZezhu** [comment]
Hi Jenny,

Thank you for your quick response. 

I carefully installed the phoebe and phoebe-QE in my computer, so I think I am using the patched version. Actually I never used the QE before. 

Cheers,
zezhu

**Comment by jcoulter12** [comment]
Hi Zezhu, 

Ok, let's make sure the patched version of QE has been done correctly. Can you look in 
phoebe-quantum-espresso/PW/src/c_bands.f90

and tell me if right at the top of the file, you see:
! Phoebe
module pw_phoebe

I am wondering if something went wrong for you when you tried to do: 
git checkout phoebe-qe-6.7.0

Best, 
Jenny

**Comment by ZengZezhu** [comment]
Hi Jenny,

There is no !phoebe and module pw_phoebe in my patched version. It seems that my installation has some issues. I will reinstall it and see what happen after "git checkout phoebe-qe-6.7.0". Thank you!

Cheers,
zezhu

**Comment by jcoulter12** [comment]
Hi Zezhu, 

Sounds good. Do let me know if you encounter any other issues, but once you confirm this solves the problem, I'll close the git issue. 

Best, 
Jenny

**Comment by ZengZezhu** [comment]
Hi Jenny,

below is the outputs when run the command of "git checkout phoebe-qe-6.7.0"


[u3004964@hpc2021 phoebe-quantum-espresso]$ git checkout phoebe-qe-6.7.0
Updating files: 100% (2330/2330), done.
Branch 'phoebe-qe-6.7.0' set up to track remote branch 'phoebe-qe-6.7.0' from 'origin'.
Switched to a new branch 'phoebe-qe-6.7.0'

Now I also can see the information that you mentioned in the c_bands.f90., and the step-2 can be performed well without errors.

Thank you for your useful help!

Cheers,
zezhu

**Comment by ZengZezhu** [comment]
Hi Jenny,

steps1-5 have no problems. It is confused for me for step-6 of Wannierization. 

When I run the "mpirun -np 4 /path/to/phoebe-quantum-espresso/bin/wannier90.x -pp si", I encountered this output:

Job Start  Time is 2022/07/26 -- 14:51:26
At line 98 of file ../wannier_prog.F90 (unit = 10, file = 'si.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
At line 98 of file ../wannier_prog.F90 (unit = 10, file = 'si.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
At line 98 of file ../wannier_prog.F90 (unit = 10, file = 'si.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:............

While I try to run the next step in step-6 using "pw2wannier90.x -in pw2wan.in > pw2wan.out". I see that the pw2wan.out is correct. What should I do for this case?

Cheers,
zezhu

**Comment by jcoulter12** [comment]
Hi Zezhu, 

As strange as this might sound, I feel I have had this issue before with QE and the solution was to remove si.werr. Genuinely might be an issue with your filesystem being unable to delete that file. 

Also, I had another thought about your first comment on this issue -- if you didn't change anything in the example input files, Si should not be metallic. To confirm for yourself that your scf calculation produced an insulator, you should look for a line similar to: 
     highest occupied, lowest unoccupied level (ev):     
in your scf.out file. 

Best, 
Jenny

**Comment by ZengZezhu** [comment]
Hi Jenny,

do I need to remove the si.werr file by myself? If it is, thats so troublesome. :) Different systems may encounter this same issue every time.  I also do not see this file in my document of calculations. 

I checked the scf.out file and found that the highest/lowest level are 6.2376 and 6.8644 eV, respectively, which is an insulator.

Cheers,
zezhu

**Comment by jcoulter12** [comment]
Hi Zezhu, 

Yes, but you should only have to remove it once -- it's possible that file was improperly closed, and now can't be reopened. It's likely happening because the calculation was killed previously while this file was open, or because the file is being written somewhere you don't have permissions to access, something strange like that. 

It's not in the tutorial because it actually has nothing to do with Phoebe, si.werr is actually just a standard error file from Wannier90.  This is an error which is occasionally encountered while using Fortran codes. It can happen sometimes when you run regular QE, as shown here:
https://www.mail-archive.com/users@lists.quantum-espresso.org/msg41510.html

Also, good to confirm this about Si being insulating. 

Let me know if the error persists after you remove the file once. If so, perhaps your QE needs to be built differently, and we can think about that. 
Jenny

**Comment by jcoulter12** [comment]
Ah, wait a moment -- this error is actually quite strange, as I see now it's coming from your very first run of Wannier90, the `mpirun -np 4 /path/to/phoebe-quantum-espresso/bin/wannier90.x -pp si` step. Sorry to have read this wrong in your comment. 

Are you sure there were no other error message? It seems quite strange Wannier90 would complain about not being able to remove that file, as there's no reason it should not exist at that point.

**Comment by ZengZezhu** [comment]
For step1-5, there is no error. Just for step-6.1,  when I run "mpirun -np 4 /path/to/phoebe-quantum-espresso/bin/wannier90.x -pp si", I encountered this error. :)

Actually yesterday even I deleted the si.werr, this error still exists. I am so confused now.

**Comment by ZengZezhu** [comment]
I am also re-performing this example from the start of step-1 within a new folder and see what happened for this.

**Comment by jcoulter12** [comment]
So far, no one has reported this issue, and I again mention that it's actually something happening with Wannier90... but I'm sure if you want to try, we can figure it out together. 

I think a new directory is not a bad idea. Also, it might be good to confirm that you are not out of memory in that directory's location.

**Comment by jcoulter12** [comment]
The other thing I can think of is -- are you sure Wannier90 built correctly when you built QE in step 1? You can try this again by just typing `make w90` in your QE directory and confirming it doesn't output any errors. Could be good to rebuild anyway to be sure.

**Comment by ZengZezhu** [comment]
Ah, I just found a solution just now. 

When I use the "wannier90.x -pp si" to run it, there is no error! just a note like this:Note: 
The following floating-point exceptions are signalling: IEEE_DENORMAL.

Maybe the error comes from the parallel ?? I think thats possible because each of supercomputer system is at least slightly different.

**Comment by ZengZezhu** [comment]
> t doesn't output any errors. Cou

Yes, I will also test this again. Thank you!

**Comment by ZengZezhu** [comment]
Now I am doing some testings by following your suggestions
1. re-compile w90
2. re-perform the example in a new folder

Once I have some results, I will report in this.

**Comment by jcoulter12** [comment]
Actually, that makes sense. I will likely update the tutorial to remove the suggestion of a parallel run on that command. I think in some cases it will work fine, but if it also can be troublesome, I will just update the docs. It's a quick run anyway and I doubt it benefits from using multiple processes. 

Ok, let me know how it goes.

**Comment by ZengZezhu** [comment]
Hi Jenny,

Now I am confident that the compile of w90 is successful.
For me, I think the issue at least can be solved by discarding the parallel. 

Re-perform the calculations also encountered this issue once I used the parallel.:)

Cheers,
zezhu

**Comment by jcoulter12** [comment]
Hi Zezhu, 

Thanks for reporting back. I'll update the docs now to reflect this so that it doesn't cause anyone else a problem. Let us know if you have any other questions or issues while using the code!

Best, 
Jenny

**Comment by ZengZezhu** [comment]
Hi Jenny,

BTW, I see the result of electrical conductivity of silicon is slightly anisotropic, is this correct? I also checked the results of reference folder, and it has the same situation.

**Comment by jcoulter12** [comment]
Hi Zezhu, 

Yes, it's no issue. It's because symmetries aren't on in the example case, and it's a relatively poorly converged calculation for the sake of a quick example. Add this line to the electronWannierTransport.in
useSymmetries = true
And it should then be symmetric.

**Comment by ZengZezhu** [comment]
Thank you for your help! I got it. This issue seems to be solved well.

 If I still have other issues and if it necessary (I could not solve it by myself), I will reopen a window to report. Thanks!

**Comment by jcoulter12** [comment]
Hi Zezhu -- looks like you reopened this by accident, I'm closing it. Feel free to open an new one if you encounter a problem, we're happy to help!
-- Jenny

**Comment by ZengZezhu** [comment]
Thank you!
