### ISSUE TITLE
How to use Phobte to distinguish NorU scattering or calculate U/N relaxation time?

### ISSUE THREAD

**Issue by RongkunChen** [mir-group/phoebe#179]

**Comment by jcoulter12** [comment]
Hi, 

You can do this for Phonon transport lifetimes following the discussion here: 
https://github.com/mir-group/phoebe/discussions/176#discussioncomment-5118200

Let me know if there is anything else you need or if you have trouble using that branch. I will likely soon merge it into develop branch and add it to the documentation as well. 

Best, 
Jenny

**Comment by RongkunChen** [comment]
Jenny,
In the process of solving the thermal conductivity, the total relaxation time or scattering rate seems to include three directions: XX, YY, ZZ. Then how should I distinguish the scattering rate or relaxation time in each direction?


Best,
Rongkun Chen




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jenny ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mir-group/phoebe] How to use Phobte to distinguish NorU scattering or calculate U/N relaxation time? (Issue #179)





 
Hi,
 
You can do this for Phonon transport lifetimes following the discussion here:
 #176 (reply in thread)
 
Let me know if there is anything else you need or if you have trouble using that branch. I will likely soon merge it into develop branch and add it to the documentation as well.
 
Best,
 Jenny

**Comment by jcoulter12** [comment]
Hi Rongkun, 

Is this in the output of the U and N times? Looking at how this data is output from the code, I am unsure of how that could happen. Could you clarify for me the procedure you ran to find that the lifetimes have XX, YY and ZZ components? 

Best, 
Jenny
