### ISSUE TITLE
Progress bar update

### ISSUE THREAD

**Issue by anjohan** [mir-group/phoebe#40]
Instead of our own LoopPrint implementation, we could use some preexisting library that produces more compact output.

I looked around the internet and found a couple of promising alternatives:

- [indicators](https://github.com/p-ranav/indicators): Fully-featured progress bar and spinner library, with support for things like nested progress bars (could be useful for the batched implementation).
- [cpptqdm](https://github.com/aminnj/cpptqdm): Lightweight progress bar that covers the basics.

**Comment by cepellotti** [comment]
I just looked at the examples. The more compact output is fine as long as your task takes little time to complete. I have a doubt if this is the best choice for HPC applications. The code runs on the scheduler, and you may want to see timestamps to get an idea about how quickly the code is proceeding. This may not be clear with a progress bar (think at a code that runs for several hours, possibly days).
